// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKEVfFOaQqTR8u_jpr_F9adtsKDMFSf1c',
    appId: '1:668451917257:web:1ab3fb7be0f51a39452c18',
    messagingSenderId: '668451917257',
    projectId: 'creativ-ai',
    authDomain: 'creativ-ai.firebaseapp.com',
    storageBucket: 'creativ-ai.appspot.com',
    measurementId: 'G-SVFKBML395',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZGxvHPvG3zeZRhlgczaSzVMXl4v1-0sk',
    appId: '1:668451917257:android:0d7228356f7906b7452c18',
    messagingSenderId: '668451917257',
    projectId: 'creativ-ai',
    storageBucket: 'creativ-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwrXP8-PQEtHaO1tjHkdZKAlEDkvyAcio',
    appId: '1:668451917257:ios:4a63e307b76d7f57452c18',
    messagingSenderId: '668451917257',
    projectId: 'creativ-ai',
    storageBucket: 'creativ-ai.appspot.com',
    iosBundleId: 'com.creativai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwrXP8-PQEtHaO1tjHkdZKAlEDkvyAcio',
    appId: '1:668451917257:ios:4a63e307b76d7f57452c18',
    messagingSenderId: '668451917257',
    projectId: 'creativ-ai',
    storageBucket: 'creativ-ai.appspot.com',
    iosBundleId: 'com.creativai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKEVfFOaQqTR8u_jpr_F9adtsKDMFSf1c',
    appId: '1:668451917257:web:fbba789a85f05c93452c18',
    messagingSenderId: '668451917257',
    projectId: 'creativ-ai',
    authDomain: 'creativ-ai.firebaseapp.com',
    storageBucket: 'creativ-ai.appspot.com',
    measurementId: 'G-2KX73CM7WM',
  );
}
